---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-thanos
  namespace: {{ include "olm-resources.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    {{- include "olm-resources.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: grafana-thanos
  name: grafana-thanos-token
  namespace: {{ include "olm-resources.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    {{- include "olm-resources.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "grafana-%s-binding" (include "olm-resources.namespace" .) | trunc 63 | trimSuffix "-" }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    {{- include "olm-resources.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: grafana-thanos
    namespace: {{ include "olm-resources.namespace" . }}
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io