{{ if  not .Values.baseGrafanaInstalled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-k8s-proxy
  namespace: {{ include "grafana-resources.namespace" . }}
  labels:
    app: grafana
    helm.sh/chart: {{ .Chart.Name }}
    {{- include "grafana-resources.labels" . | nindent 4 }}
type: Opaque
stringData:
  session_secret: {{ randAlphaNum 41 | quote }}
{{ end }}